### ISSUE TITLE
Build breakage observed downstream

### ISSUE THREAD

**Issue by sauclovian-g** [GaloisInc/entree-specs#7]
We observed the following in the SAW CI run:
```
COQC theories/Ref/EnTreeSpecFacts.v
File "./theories/Ref/EnTreeSpecFacts.v", line 432, characters 60-101:
Error: No such goal. The current bullet * is unfinished.

make[1]: *** [theories/Ref/EnTreeSpecFacts.vo] Error 1
```

Something must have changed upstream, as nothing changed here.

**Comment by RyanGlScott** [comment]
I looked through `saw-script`'s CI actions and discovered that [this](https://github.com/GaloisInc/saw-script/actions/runs/11252668181/job/31286780779#step:9:23) was the last succeeding job:

```
 The following actions will be performed:
  ∗ install coq-ext-lib  0.12.2 [required by coq-itree]
  ∗ install coq-paco     4.2.0  [required by entree-specs]
  ∗ install coq-itree    5.2.0  [required by entree-specs]
  ∗ install entree-specs dev*
```

And [this](https://github.com/GaloisInc/saw-script/actions/runs/11271779146/job/31345819996#step:9:23) was the first failing job:

```
 The following actions will be performed:
  ∗ install coq-paco     4.2.1  [required by entree-specs]
  ∗ install coq-ext-lib  0.12.2 [required by coq-itree]
  ∗ install coq-itree    5.2.0  [required by entree-specs]
  ∗ install entree-specs dev*
```

The only difference in the build plan arises in `coq-paco`, which uses version 4.2.0 in the succeeding job and 4.2.1 in the failing job. Unfortunately, the [`coq-paco` changelog](https://github.com/snu-sf/paco/blob/f0f813b9db221d6dc041e3544af52222d7147345/CHANGES) isn't helpful here in determining what changed. Given that the code which failed to compile involves the `pclearbot` tactic, my guess is that [this commit](https://github.com/snu-sf/paco/commit/ae2b3c9918824f2616a7e71cd85c63aa77494a1f) or [this commit](https://github.com/snu-sf/paco/commit/f0f813b9db221d6dc041e3544af52222d7147345) is the culprit.
